/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helps.view;


import helps.dao.Verificar_Usuarios_Banco;
import java.awt.Color;
import helps.pojo.pojo;
import helps.dao.Banco;
import helps.dao.Estados;
import helps.dao.cadastrar_usuario;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;





    
public class Perfil_Usuario extends javax.swing.JFrame {
    
    //escolha escolha_global;
    int id = 0;
    pojo pojo_global;
    
   
    public Perfil_Usuario(int codigo) throws SQLException {
        
        id = codigo;
        initComponents();
        preencher_campos(codigo);
        setLocationRelativeTo(null);
        Estados estadoslista = new Estados();
        List<String>Estados = estadoslista.Estados();
        
        CUsuarioEstado.setModel(new DefaultComboBoxModel(Estados.toArray()));
        
        pojo select = new pojo();
        
        CUsuarioEstado.setSelectedItem(select.getEstado());
        
    }
    
    public void preencher_campos (int codigo){
        
        Verificar_Usuarios_Banco p = new Verificar_Usuarios_Banco();
        pojo_global = p.verificar_login_usuario_unico(codigo);
        TUsuarioEmail.setText(pojo_global.getEmail());
        TUsuarioNome.setText(pojo_global.getNome());
        TUsuarioTelefone.setText(pojo_global.getTelefone());
        CUsuarioEstado.setSelectedItem(pojo_global.getEstado());
        System.out.println(pojo.estado);
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LNome = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        LSenha = new javax.swing.JLabel();
        LSobrenome = new javax.swing.JLabel();
        LEspecializacoes = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        BVoltar = new javax.swing.JButton();
        BSalvar = new javax.swing.JButton();
        TUsuarioNome = new javax.swing.JTextField();
        TSobrenome = new javax.swing.JTextField();
        TUsuarioEmail = new javax.swing.JTextField();
        TSenha = new javax.swing.JTextField();
        BVisibilidade = new javax.swing.JToggleButton();
        LTelefone = new javax.swing.JLabel();
        LEndereco = new javax.swing.JLabel();
        TEndereco = new javax.swing.JTextField();
        LCep = new javax.swing.JLabel();
        TCep = new javax.swing.JTextField();
        TUsuarioTelefone = new javax.swing.JFormattedTextField();
        CUsuarioEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Perfil do Usuário"));

        LNome.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        LNome.setText("Nome");

        LEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        LEmail.setText("E-mail");

        LSenha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        LSenha.setText("Senha");

        LSobrenome.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        LSobrenome.setText("Sobrenome");

        LEspecializacoes.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        LEspecializacoes.setText("Especializações");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trocar pneu", "Roçar grama" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setText("  FOTO");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        BVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/helps/icon/SetaEsquerda24x24.png"))); // NOI18N
        BVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVoltarActionPerformed(evt);
            }
        });

        BSalvar.setText("Salvar");
        BSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalvarActionPerformed(evt);
            }
        });

        TUsuarioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUsuarioNomeActionPerformed(evt);
            }
        });

        TSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSobrenomeActionPerformed(evt);
            }
        });

        TUsuarioEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUsuarioEmailActionPerformed(evt);
            }
        });

        BVisibilidade.setText("Escolher trabalho");
        BVisibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVisibilidadeActionPerformed(evt);
            }
        });

        LTelefone.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        LTelefone.setText("Telefone");

        LEndereco.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        LEndereco.setText("Endereço");

        LCep.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        LCep.setText("CEP");

        TUsuarioTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        TUsuarioTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUsuarioTelefoneActionPerformed(evt);
            }
        });

        CUsuarioEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CUsuarioEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUsuarioEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(BVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CUsuarioEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BVisibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LNome)
                                .addGap(39, 39, 39)
                                .addComponent(TUsuarioNome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LSobrenome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TSobrenome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LEndereco)
                                .addGap(18, 18, 18)
                                .addComponent(TEndereco))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LCep)
                                .addGap(53, 53, 53)
                                .addComponent(TCep))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LEspecializacoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LTelefone)
                                .addGap(21, 21, 21)
                                .addComponent(TUsuarioTelefone))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LEmail)
                                    .addComponent(LSenha))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TSenha)
                                    .addComponent(TUsuarioEmail))))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BVoltar)))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TUsuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNome, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LEndereco)
                    .addComponent(TEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCep)
                    .addComponent(TCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTelefone)
                    .addComponent(TUsuarioTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LEspecializacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BSalvar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BVisibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CUsuarioEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TUsuarioTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUsuarioTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TUsuarioTelefoneActionPerformed

    private void BVisibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVisibilidadeActionPerformed

    }//GEN-LAST:event_BVisibilidadeActionPerformed

    private void TUsuarioEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUsuarioEmailActionPerformed
       
      
    }//GEN-LAST:event_TUsuarioEmailActionPerformed

    private void TSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TSobrenomeActionPerformed

    private void TUsuarioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUsuarioNomeActionPerformed

    }//GEN-LAST:event_TUsuarioNomeActionPerformed

    private void BSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BSalvarActionPerformed

    private void BVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVoltarActionPerformed
     
        
        //System.out.println(pojo.Nome);
        
        escolha es = new escolha(pojo.codigo);
        es.setVisible(true);
        dispose();
    }//GEN-LAST:event_BVoltarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void CUsuarioEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUsuarioEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CUsuarioEstadoActionPerformed
        
    
    
    
   
    
    
    
    
    
    
    
    
    
   
        
        /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
     
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Perfil_Usuario().setVisible(true);                
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSalvar;
    private javax.swing.JToggleButton BVisibilidade;
    private javax.swing.JButton BVoltar;
    private javax.swing.JComboBox<String> CUsuarioEstado;
    private javax.swing.JLabel LCep;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LEndereco;
    private javax.swing.JLabel LEspecializacoes;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LSenha;
    private javax.swing.JLabel LSobrenome;
    private javax.swing.JLabel LTelefone;
    private javax.swing.JTextField TCep;
    private javax.swing.JTextField TEndereco;
    private javax.swing.JTextField TSenha;
    private javax.swing.JTextField TSobrenome;
    private javax.swing.JTextField TUsuarioEmail;
    private javax.swing.JTextField TUsuarioNome;
    private javax.swing.JFormattedTextField TUsuarioTelefone;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
